@baseUrl = http://localhost:3000/api
@authToken = <paste_token_here>

### Create Category
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Music",
  "group": "course",
  "status": "active"
}

### Get Category List
GET {{baseUrl}}/categories?page=1&limit=10
Authorization: Bearer {{authToken}}

### Get Category by ID
GET {{baseUrl}}/categories/replace-with-uuid
Authorization: Bearer {{authToken}}

### Update Category
PUT {{baseUrl}}/categories/replace-with-uuid
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Music Updated"
}

### Delete Category
DELETE {{baseUrl}}/categories/replace-with-uuid
Authorization: Bearer {{authToken}}
